# Image settings
IMAGE_SIZE_PX = 1000
OBJ_DIAM_RATIO = 0.5
GRAY_LIGHT_THRESHOLD = 0.5


# Object (center circle) settings
OBJ_GRAY_N = 2
OBJ_GRAY_MIN = 0.3
OBJ_GRAY_MAX = 0.7

OBJ_CHROM_N_INT = 2
OBJ_CHROM_INT_MIN = 0.3
OBJ_CHROM_INT_MAX = 0.7

OBJ_CHROM_N_SAT = 2
OBJ_CHROM_SAT_MIN = 0.3
OBJ_CHROM_SAT_MAX = 0.7


# Background settings
BG_GRAY_N_INT = 2
BG_GRAY_DELTA_INT_MIN = -0.4
BG_GRAY_DELTA_INT_MAX = 0.4

BG_CHROM_N_INT = 2
BG_CHROM_DELTA_INT_MIN = -0.2
BG_CHROM_DELTA_INT_MAX = 0.2

BG_CHROM_N_SAT = 2
BG_CHROM_DELTA_SAT_MIN = -0.2
BG_CHROM_DELTA_SAT_MAX = 0.5
INCLUDE_BG_CHROM_SAT_1 = true